/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2203 from the
 * contents of RPM_Dependencies.xs. Do not edit this file, edit RPM_Dependencies.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "RPM_Dependencies.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#undef Fflush
#undef Mkdir
#undef Stat
#undef Fstat

#include "rpmio.h"
#include "rpmiotypes.h"		/* XXX fnpyKey */

#include "rpmtypes.h"
#include "rpmtag.h"

#define _RPMEVR_INTERNAL
#include "rpmds.h"
#include "rpmevr.h"

#include "rpmxs.h"

void _newdep(SV * sv_deptag, char * name, SV * sv_sense, SV * sv_evr) {
    rpmTag deptag = 0;
    rpmsenseFlags sense = RPMSENSE_ANY;
    rpmds Dep;
    char * evr = NULL;
    dSP;

    if (sv_deptag && SvOK(sv_deptag))
        deptag = sv2constant(sv_deptag, "rpmtag");
    if (sv_sense && SvOK(sv_sense))
        sense = sv2constant(sv_sense, "rpmsenseflags");
    if (sv_evr && SvOK(sv_evr))
        evr = SvPV_nolen(sv_evr);
    Dep = rpmdsSingle(deptag, 
        name,
        evr ? evr : "", sense);
    if (Dep) {
        XPUSHs(sv_2mortal(sv_setref_pv(newSVpv("", 0), "RPM::Dependencies", Dep)));
    }
    PUTBACK;
}

#line 54 "RPM_Dependencies.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 106 "RPM_Dependencies.c"

XS(XS_RPM__Dependencies_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "class, header, sv_tag");
    {
	const char *	class = (const char *)SvPV_nolen(ST(0));
	Header	header;
	SV *	sv_tag = ST(2);
#line 54 "RPM_Dependencies.xs"
    rpmTag tag = 0;
#line 124 "RPM_Dependencies.c"
	rpmds	RETVAL;

    if (sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG))
        header = (Header)SvIV((SV*)SvRV( ST(1) ));
    else {
        warn( "RPM::Dependencies::new() -- header is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 56 "RPM_Dependencies.xs"
    tag = sv2constant(sv_tag, "rpmtag");
    RETVAL = rpmdsNew(header, tag, 0);
    if (RETVAL) RETVAL = rpmdsInit(RETVAL);
#line 137 "RPM_Dependencies.c"
	ST(0) = sv_newmortal();
        sv_setref_pv( ST(0), "RPM::Dependencies", (void*)RETVAL );
    }
    XSRETURN(1);
}


XS(XS_RPM__Dependencies_create); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_create)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 3 || items > 5)
       croak_xs_usage(cv,  "perlclass, sv_tag, name, sv_sense = NULL, sv_evr = NULL");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char *	perlclass = (char *)SvPV_nolen(ST(0));
	SV *	sv_tag = ST(1);
	char *	name = (char *)SvPV_nolen(ST(2));
	SV *	sv_sense;
	SV *	sv_evr;

	if (items < 4)
	    sv_sense = NULL;
	else {
	    sv_sense = ST(3);
	}

	if (items < 5)
	    sv_evr = NULL;
	else {
	    sv_evr = ST(4);
	}
#line 70 "RPM_Dependencies.xs"
    PUTBACK;
    _newdep(sv_tag, name, sv_sense, sv_evr);
    SPAGAIN;
#line 179 "RPM_Dependencies.c"
	PUTBACK;
	return;
    }
}


XS(XS_RPM__Dependencies_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Dep");
    {
	rpmds	Dep;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::DESTROY() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 78 "RPM_Dependencies.xs"
    Dep = rpmdsFree(Dep);
#line 207 "RPM_Dependencies.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_RPM__Dependencies_count); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_count)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Dep");
    {
	rpmds	Dep;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::count() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 84 "RPM_Dependencies.xs"
    RETVAL = rpmdsCount(Dep);
#line 236 "RPM_Dependencies.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Dependencies_index); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_index)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Dep");
    {
	rpmds	Dep;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::index() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 92 "RPM_Dependencies.xs"
    RETVAL = rpmdsIx(Dep);
#line 266 "RPM_Dependencies.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Dependencies_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_init)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Dep");
    {
	rpmds	Dep;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::init() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 100 "RPM_Dependencies.xs"
    rpmdsInit(Dep);
#line 294 "RPM_Dependencies.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_RPM__Dependencies_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_next)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Dep");
    {
	rpmds	Dep;
#line 106 "RPM_Dependencies.xs"
    char val[16];
    int idx = 0;
#line 315 "RPM_Dependencies.c"
	char *	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::next() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 109 "RPM_Dependencies.xs"
    if ((idx = rpmdsNext(Dep)) ==  -1)
        RETVAL = NULL;
    else  {
        snprintf(val, 12, idx == 0 ? "%dE0" : "%d", idx);
        RETVAL = val;
    }
#line 332 "RPM_Dependencies.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_RPM__Dependencies_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Dep");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	rpmds	Dep;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::name() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 122 "RPM_Dependencies.xs"
    CHECK_RPMDS_IX(Dep);
    XPUSHs(sv_2mortal(newSVpv(rpmdsN(Dep), 0)));
#line 363 "RPM_Dependencies.c"
	PUTBACK;
	return;
    }
}


XS(XS_RPM__Dependencies_flags); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_flags)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Dep");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	rpmds	Dep;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::flags() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 129 "RPM_Dependencies.xs"
    CHECK_RPMDS_IX(Dep);
    XPUSHs(sv_2mortal(newSViv(rpmdsFlags(Dep))));
#line 394 "RPM_Dependencies.c"
	PUTBACK;
	return;
    }
}


XS(XS_RPM__Dependencies_evr); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_evr)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Dep");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	rpmds	Dep;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::evr() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 136 "RPM_Dependencies.xs"
    CHECK_RPMDS_IX(Dep);
    XPUSHs(sv_2mortal(newSVpv(rpmdsEVR(Dep), 0)));
#line 425 "RPM_Dependencies.c"
	PUTBACK;
	return;
    }
}


XS(XS_RPM__Dependencies_color); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_color)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Dep");
    {
	rpmds	Dep;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::color() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 143 "RPM_Dependencies.xs"
    RETVAL = rpmdsColor(Dep);
#line 455 "RPM_Dependencies.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Dependencies___find); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies___find)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "Dep, depb");
    {
	rpmds	Dep;
	rpmds	depb;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::__find() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };

    if (sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG))
        depb = (rpmds)SvIV((SV*)SvRV( ST(1) ));
    else {
        warn( "RPM::Dependencies::__find() -- depb is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 152 "RPM_Dependencies.xs"
    RETVAL = rpmdsFind(Dep, depb);
#line 493 "RPM_Dependencies.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Dependencies___merge); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies___merge)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "Dep, depb");
    {
	rpmds	Dep;
	rpmds	depb;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::__merge() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };

    if (sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG))
        depb = (rpmds)SvIV((SV*)SvRV( ST(1) ));
    else {
        warn( "RPM::Dependencies::__merge() -- depb is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 161 "RPM_Dependencies.xs"
    RETVAL = rpmdsMerge(&Dep, depb);
#line 531 "RPM_Dependencies.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Dependencies_overlap); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_overlap)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "Dep1, Dep2");
    {
	rpmds	Dep1;
	rpmds	Dep2;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep1 = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::overlap() -- Dep1 is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };

    if (sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG))
        Dep2 = (rpmds)SvIV((SV*)SvRV( ST(1) ));
    else {
        warn( "RPM::Dependencies::overlap() -- Dep2 is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 170 "RPM_Dependencies.xs"
    CHECK_RPMDS_IX(Dep1);
    CHECK_RPMDS_IX(Dep2);
    RETVAL = rpmdsCompare(Dep1, Dep2);
#line 571 "RPM_Dependencies.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Dependencies___info); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies___info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Dep");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	rpmds	Dep;
#line 180 "RPM_Dependencies.xs"
    rpmsenseFlags flag;
    I32 gimme = GIMME_V;
#line 595 "RPM_Dependencies.c"

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::__info() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 183 "RPM_Dependencies.xs"
    CHECK_RPMDS_IX(Dep);
    if (gimme == G_SCALAR) {
        XPUSHs(sv_2mortal(newSVpv(rpmdsDNEVR(Dep), 0)));
    } else {
        switch (rpmdsTagN(Dep)) {
            case RPMTAG_PROVIDENAME:
                XPUSHs(sv_2mortal(newSVpv("P", 0)));
            break;
            case RPMTAG_REQUIRENAME:
                XPUSHs(sv_2mortal(newSVpv("R", 0)));
            break;
            case RPMTAG_CONFLICTNAME:
                XPUSHs(sv_2mortal(newSVpv("C", 0)));
            break;
            case RPMTAG_OBSOLETENAME:
                XPUSHs(sv_2mortal(newSVpv("O", 0)));
            break;
            case RPMTAG_TRIGGERNAME:
                XPUSHs(sv_2mortal(newSVpv("T", 0)));
            break;
            default:
            break;
        }
        XPUSHs(sv_2mortal(newSVpv(rpmdsN(Dep), 0)));
        flag = rpmdsFlags(Dep);
        XPUSHs(sv_2mortal(newSVpvf("%s%s%s",
                        flag & RPMSENSE_LESS ? "<" : "",
                        flag & RPMSENSE_GREATER ? ">" : "",
                        flag & RPMSENSE_EQUAL ? "=" : "")));
        XPUSHs(sv_2mortal(newSVpv(rpmdsEVR(Dep), 0)));
    }
#line 635 "RPM_Dependencies.c"
	PUTBACK;
	return;
    }
}


XS(XS_RPM__Dependencies_tag); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_tag)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Dep");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	rpmds	Dep;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::tag() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 219 "RPM_Dependencies.xs"
    XPUSHs(sv_2mortal(newSViv(rpmdsTagN(Dep))));
#line 665 "RPM_Dependencies.c"
	PUTBACK;
	return;
    }
}


XS(XS_RPM__Dependencies___nopromote); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies___nopromote)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "Dep, sv_nopromote = NULL");
    {
	rpmds	Dep;
	SV *	sv_nopromote;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::__nopromote() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };

	if (items < 2)
	    sv_nopromote = NULL;
	else {
	    sv_nopromote = ST(1);
	}
#line 226 "RPM_Dependencies.xs"
    if (sv_nopromote == NULL) {
        RETVAL = rpmdsNoPromote(Dep);
    } else {
        RETVAL = rpmdsSetNoPromote(Dep, SvIV(sv_nopromote));
    }
#line 706 "RPM_Dependencies.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Dependencies_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 4)
       croak_xs_usage(cv,  "Dep, name, sv_sense = NULL, sv_evr = NULL");
    {
	rpmds	Dep;
	char *	name = (char *)SvPV_nolen(ST(1));
	SV *	sv_evr;
	SV *	sv_sense;
#line 242 "RPM_Dependencies.xs"
    rpmsenseFlags sense = RPMSENSE_ANY;
    rpmds Deptoadd;
    char * evr = NULL;
#line 732 "RPM_Dependencies.c"
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::add() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };

	if (items < 4)
	    sv_evr = NULL;
	else {
	    sv_evr = ST(3);
	}

	if (items < 3)
	    sv_sense = NULL;
	else {
	    sv_sense = ST(2);
	}
#line 246 "RPM_Dependencies.xs"
    RETVAL = 0;
    if (sv_sense && SvOK(sv_sense))
        sense = sv2constant(sv_sense, "rpmsenseflags");
    if (sv_evr && SvOK(sv_evr))
        evr = SvPV_nolen(sv_evr);
    Deptoadd = rpmdsSingle(rpmdsTagN(Dep), name,
         evr ? evr : "", sense);
    if (Deptoadd) {
        rpmdsMerge(&Dep, Deptoadd);
        Deptoadd = rpmdsFree(Deptoadd);
        RETVAL = 1;
    }
#line 767 "RPM_Dependencies.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Dependencies___matchheader); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies___matchheader)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "Dep, header, sv_nopromote = NULL");
    {
	Header	header;
	SV *	sv_nopromote;
	rpmds	Dep;
#line 267 "RPM_Dependencies.xs"
    int nopromote = 0;
#line 790 "RPM_Dependencies.c"
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG))
        header = (Header)SvIV((SV*)SvRV( ST(1) ));
    else {
        warn( "RPM::Dependencies::__matchheader() -- header is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };

	if (items < 3)
	    sv_nopromote = NULL;
	else {
	    sv_nopromote = ST(2);
	}

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::__matchheader() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 269 "RPM_Dependencies.xs"
    if (sv_nopromote != NULL)
        nopromote = SvIV(sv_nopromote);    
    RETVAL = _header_vs_dep(header, Dep, nopromote);
#line 817 "RPM_Dependencies.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Dependencies___matchheadername); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Dependencies___matchheadername)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "Dep, header, sv_nopromote = NULL");
    {
	rpmds	Dep;
	Header	header;
	SV *	sv_nopromote;
#line 281 "RPM_Dependencies.xs"
    int nopromote = 0;
#line 840 "RPM_Dependencies.c"
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Dep = (rpmds)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Dependencies::__matchheadername() -- Dep is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };

    if (sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG))
        header = (Header)SvIV((SV*)SvRV( ST(1) ));
    else {
        warn( "RPM::Dependencies::__matchheadername() -- header is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };

	if (items < 3)
	    sv_nopromote = NULL;
	else {
	    sv_nopromote = ST(2);
	}
#line 283 "RPM_Dependencies.xs"
    if (sv_nopromote != NULL)
        nopromote = SvIV(sv_nopromote);
    RETVAL = _headername_vs_dep(header, Dep, nopromote);
#line 867 "RPM_Dependencies.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_RPM__Dependencies); /* prototype to pass -Wmissing-prototypes */
XS(boot_RPM__Dependencies)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("RPM::Dependencies::new", XS_RPM__Dependencies_new, file, "$$$");
        (void)newXSproto_portable("RPM::Dependencies::create", XS_RPM__Dependencies_create, file, "$$$;$$");
        (void)newXSproto_portable("RPM::Dependencies::DESTROY", XS_RPM__Dependencies_DESTROY, file, "$");
        (void)newXSproto_portable("RPM::Dependencies::count", XS_RPM__Dependencies_count, file, "$");
        (void)newXSproto_portable("RPM::Dependencies::index", XS_RPM__Dependencies_index, file, "$");
        (void)newXSproto_portable("RPM::Dependencies::init", XS_RPM__Dependencies_init, file, "$");
        (void)newXSproto_portable("RPM::Dependencies::next", XS_RPM__Dependencies_next, file, "$");
        (void)newXSproto_portable("RPM::Dependencies::name", XS_RPM__Dependencies_name, file, "$");
        (void)newXSproto_portable("RPM::Dependencies::flags", XS_RPM__Dependencies_flags, file, "$");
        (void)newXSproto_portable("RPM::Dependencies::evr", XS_RPM__Dependencies_evr, file, "$");
        (void)newXSproto_portable("RPM::Dependencies::color", XS_RPM__Dependencies_color, file, "$");
        (void)newXSproto_portable("RPM::Dependencies::__find", XS_RPM__Dependencies___find, file, "$$");
        (void)newXSproto_portable("RPM::Dependencies::__merge", XS_RPM__Dependencies___merge, file, "$$");
        (void)newXSproto_portable("RPM::Dependencies::overlap", XS_RPM__Dependencies_overlap, file, "$$");
        (void)newXSproto_portable("RPM::Dependencies::__info", XS_RPM__Dependencies___info, file, "$");
        (void)newXSproto_portable("RPM::Dependencies::tag", XS_RPM__Dependencies_tag, file, "$");
        (void)newXSproto_portable("RPM::Dependencies::__nopromote", XS_RPM__Dependencies___nopromote, file, "$;$");
        (void)newXSproto_portable("RPM::Dependencies::add", XS_RPM__Dependencies_add, file, "$$;$$");
        (void)newXSproto_portable("RPM::Dependencies::__matchheader", XS_RPM__Dependencies___matchheader, file, "$$;$");
        (void)newXSproto_portable("RPM::Dependencies::__matchheadername", XS_RPM__Dependencies___matchheadername, file, "$$;$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

