/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2203 from the
 * contents of RPM_PackageIterator.xs. Do not edit this file, edit RPM_PackageIterator.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "RPM_PackageIterator.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#undef Fflush
#undef Mkdir
#undef Stat
#undef Fstat

#include <stdio.h>
#include <string.h>
#include <utime.h>

#include <rpmio.h>
#include "rpmiotypes.h"

#include "rpmtypes.h"
#include "rpmtag.h"
#include "rpmdb.h"

#include "rpmte.h"
#include "rpmts.h"

#include "misc.h"

#include "rpmcli.h"

#include "rpmxs.h"

#line 40 "RPM_PackageIterator.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 92 "RPM_PackageIterator.c"

XS(XS_RPM__PackageIterator_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__PackageIterator_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1 || items > 4)
       croak_xs_usage(cv,  "class, sv_tagname = NULL, sv_tagvalue = NULL, keylen = 0");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	char *	class = (char *)SvPV_nolen(ST(0));
	SV *	sv_tagname;
	SV *	sv_tagvalue;
	int	keylen;
#line 41 "RPM_PackageIterator.xs"
    rpmts ts = rpmtsCreate();
#line 113 "RPM_PackageIterator.c"

	if (items < 2)
	    sv_tagname = NULL;
	else {
	    sv_tagname = ST(1);
	}

	if (items < 3)
	    sv_tagvalue = NULL;
	else {
	    sv_tagvalue = ST(2);
	}

	if (items < 4)
	    keylen = 0;
	else {
	    keylen = (int)SvIV(ST(3));
	}
#line 43 "RPM_PackageIterator.xs"
    PUTBACK;
    _newiterator(ts, sv_tagname, sv_tagvalue, keylen);
    SPAGAIN;
    /* FIXME: ts = rpmtsFree(ts); */
#line 137 "RPM_PackageIterator.c"
	PUTBACK;
	return;
    }
}


XS(XS_RPM__PackageIterator_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__PackageIterator_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "mi");
    {
	rpmmi	mi;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        mi = (rpmmi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::PackageIterator::DESTROY() -- mi is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 52 "RPM_PackageIterator.xs"
    mi = rpmmiFree(mi);
#line 165 "RPM_PackageIterator.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_RPM__PackageIterator_prune); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__PackageIterator_prune)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "mi, ...");
    {
	rpmmi	mi;
#line 58 "RPM_PackageIterator.xs"
    uint32_t * exclude = NULL;
    int exclude_count = 0;
    int i = 0;
#line 187 "RPM_PackageIterator.c"

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        mi = (rpmmi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::PackageIterator::prune() -- mi is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 62 "RPM_PackageIterator.xs"
    exclude_count = items - 1;
    exclude = malloc(exclude_count * sizeof(*exclude));
    for (i = 1; i < items; i++) {
        if (!SvIOK(ST(i))) { /* TODO: */ }
        exclude[i - 1] = SvIV(ST(i));
    }
    rpmmiPrune(mi, exclude, exclude_count, 0);
    _free(exclude);
#line 204 "RPM_PackageIterator.c"
    }
    XSRETURN(1);
}


XS(XS_RPM__PackageIterator_getoffset); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__PackageIterator_getoffset)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "mi");
    {
	rpmmi	mi;
	unsigned int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        mi = (rpmmi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::PackageIterator::getoffset() -- mi is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 75 "RPM_PackageIterator.xs"
    RETVAL = rpmmiInstance(mi);
#line 233 "RPM_PackageIterator.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__PackageIterator_count); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__PackageIterator_count)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "mi");
    {
	rpmmi	mi;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        mi = (rpmmi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::PackageIterator::count() -- mi is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 83 "RPM_PackageIterator.xs"
    RETVAL = rpmmiCount(mi);
#line 263 "RPM_PackageIterator.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__PackageIterator_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__PackageIterator_next)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "mi");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	rpmmi	mi;
#line 91 "RPM_PackageIterator.xs"
    Header header = NULL;
#line 286 "RPM_PackageIterator.c"

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        mi = (rpmmi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::PackageIterator::next() -- mi is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 93 "RPM_PackageIterator.xs"
    header = rpmmiNext(mi);
    if (header) {
        XPUSHs(sv_2mortal(sv_setref_pv(newSVpv("", 0), "RPM::Header", headerLink(header))));
    }
#line 299 "RPM_PackageIterator.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_RPM__PackageIterator); /* prototype to pass -Wmissing-prototypes */
XS(boot_RPM__PackageIterator)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("RPM::PackageIterator::new", XS_RPM__PackageIterator_new, file, "$;$$$");
        (void)newXSproto_portable("RPM::PackageIterator::DESTROY", XS_RPM__PackageIterator_DESTROY, file, "$");
        (void)newXSproto_portable("RPM::PackageIterator::prune", XS_RPM__PackageIterator_prune, file, "$;@");
        (void)newXSproto_portable("RPM::PackageIterator::getoffset", XS_RPM__PackageIterator_getoffset, file, "$");
        (void)newXSproto_portable("RPM::PackageIterator::count", XS_RPM__PackageIterator_count, file, "$");
        (void)newXSproto_portable("RPM::PackageIterator::next", XS_RPM__PackageIterator_next, file, "$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

