/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2203 from the
 * contents of RPM_Files.xs. Do not edit this file, edit RPM_Files.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "RPM_Files.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#undef Fflush
#undef Mkdir
#undef Stat
#undef Fstat

#include "../config.h"
/* XXX artifacts needed to include "rpmio_internal.h" w/o "system.h" */
void * vmefail(size_t size);
#define xstrdup(_str)   (strcpy((malloc(strlen(_str)+1) ? : vmefail(strlen(_str)+1)), (_str)))

#include "rpmio_internal.h"
#include "rpmtypes.h"
#include "rpmtag.h"
#include "rpmfi.h"

#line 30 "RPM_Files.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 82 "RPM_Files.c"

XS(XS_RPM__Files_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 3)
       croak_xs_usage(cv,  "class, header, ts = NULL");
    {
	char *	class = (char *)SvPV_nolen(ST(0));
	Header	header;
	rpmts	ts;
	rpmfi	RETVAL;

    if (sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG))
        header = (Header)SvIV((SV*)SvRV( ST(1) ));
    else {
        warn( "RPM::Files::new() -- header is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };

	if (items < 3)
	    ts = NULL;
	else {
    if (sv_isobject(ST(2)) && (SvTYPE(SvRV(ST(2))) == SVt_PVMG))
	ts = (rpmts)SvIV((SV*)SvRV( ST(2) ));
    else {
	warn( "RPM::Files::new() -- ts is not a blessed SV reference" );
	XSRETURN_UNDEF;
    };
	}
#line 30 "RPM_Files.xs"
    RETVAL = rpmfiNew(ts, header, RPMTAG_BASENAMES, 0);
#line 119 "RPM_Files.c"
	ST(0) = sv_newmortal();
        sv_setref_pv( ST(0), "RPM::Files", (void*)RETVAL );
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	rpmfi	Files;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::DESTROY() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 38 "RPM_Files.xs"
    Files = rpmfiFree(Files);
#line 150 "RPM_Files.c"
	PUTBACK;
	return;
    }
}


XS(XS_RPM__Files_count); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_count)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::count() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 44 "RPM_Files.xs"
    RETVAL = rpmfiFC(Files);
#line 180 "RPM_Files.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_init)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::init() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 52 "RPM_Files.xs"
    rpmfiInit(Files, 0);
#line 208 "RPM_Files.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_RPM__Files_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_next)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
#line 58 "RPM_Files.xs"
    char val[16];
    int idx = 0;
#line 229 "RPM_Files.c"
	char *	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::next() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 61 "RPM_Files.xs"
    if ((idx = rpmfiNext(Files)) == -1) {
        RETVAL = NULL;
    } else {
        snprintf(val, 12, idx == 0 ? "%dE0" : "%d", idx);
        RETVAL = val;
    }
#line 246 "RPM_Files.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_count_dir); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_count_dir)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::count_dir() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 74 "RPM_Files.xs"
    RETVAL = rpmfiDC(Files);
#line 276 "RPM_Files.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_init_dir); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_init_dir)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::init_dir() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 83 "RPM_Files.xs"
    rpmfiInitD(Files, 0);
#line 304 "RPM_Files.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_RPM__Files_next_dir); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_next_dir)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
#line 89 "RPM_Files.xs"
    char val[16];
    int idx = 0;
#line 325 "RPM_Files.c"
	char *	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::next_dir() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 92 "RPM_Files.xs"
    if ((idx = rpmfiNextD(Files)) == -1) {
        RETVAL = NULL;
    } else {
        snprintf(val, 12, idx == 0 ? "%dE0" : "%d", idx);
        RETVAL = val;
    }
#line 342 "RPM_Files.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_RPM__Files__compare); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files__compare)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "Files, Fb");
    {
	rpmfi	Files;
	rpmfi	Fb;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::_compare() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };

    if (sv_isobject(ST(1)) && (SvTYPE(SvRV(ST(1))) == SVt_PVMG))
        Fb = (rpmfi)SvIV((SV*)SvRV( ST(1) ));
    else {
        warn( "RPM::Files::_compare() -- Fb is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 106 "RPM_Files.xs"
    RETVAL = rpmfiCompare(Files, Fb);
#line 380 "RPM_Files.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_filename); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_filename)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	const char *	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::filename() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 114 "RPM_Files.xs"
    RETVAL = rpmfiFN(Files);
#line 410 "RPM_Files.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_dirname); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_dirname)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	const char *	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::dirname() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 122 "RPM_Files.xs"
    RETVAL = rpmfiDN(Files);
#line 440 "RPM_Files.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_basename); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_basename)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	const char *	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::basename() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 130 "RPM_Files.xs"
    RETVAL = rpmfiBN(Files);
#line 470 "RPM_Files.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_fflags); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_fflags)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	unsigned int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::fflags() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 138 "RPM_Files.xs"
    RETVAL = rpmfiFFlags(Files);
#line 500 "RPM_Files.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_mode); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_mode)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	unsigned int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::mode() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 146 "RPM_Files.xs"
    RETVAL = rpmfiFMode(Files);
#line 530 "RPM_Files.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_digest); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_digest)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	rpmfi	Files;
#line 154 "RPM_Files.xs"
    const unsigned char * digest;
    int algop = 0;
    size_t lenp = 0;
#line 555 "RPM_Files.c"

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::digest() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 158 "RPM_Files.xs"
    if ((digest = rpmfiDigest(Files, &algop, &lenp)) != NULL
    /* return undef if empty */) {
	if (lenp && strlen((const char*)digest)) {
	    const char * hexDigest = pgpHexStr(digest, lenp);
	    XPUSHs(sv_2mortal(newSViv(algop)));
	    XPUSHs(sv_2mortal(newSVpv(hexDigest, lenp<<1)));
	}
    }
#line 572 "RPM_Files.c"
	PUTBACK;
	return;
    }
}


XS(XS_RPM__Files_link); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_link)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	const char *	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::link() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 171 "RPM_Files.xs"
    RETVAL = rpmfiFLink(Files);
#line 602 "RPM_Files.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_user); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_user)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	const char *	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::user() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 179 "RPM_Files.xs"
    RETVAL = rpmfiFUser(Files);
#line 632 "RPM_Files.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_group); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_group)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	const char *	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::group() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 187 "RPM_Files.xs"
    RETVAL = rpmfiFGroup(Files);
#line 662 "RPM_Files.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_inode); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_inode)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::inode() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 195 "RPM_Files.xs"
    RETVAL = rpmfiFInode(Files);
#line 692 "RPM_Files.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_size); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_size)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::size() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 203 "RPM_Files.xs"
    RETVAL = rpmfiFSize(Files);
#line 722 "RPM_Files.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_dev); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_dev)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::dev() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 211 "RPM_Files.xs"
    RETVAL = rpmfiFRdev(Files);
#line 752 "RPM_Files.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_color); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_color)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::color() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 219 "RPM_Files.xs"
    RETVAL = rpmfiFColor(Files);
#line 782 "RPM_Files.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_class); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_class)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	const char *	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::class() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 227 "RPM_Files.xs"
    RETVAL = rpmfiFClass(Files);
#line 812 "RPM_Files.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_RPM__Files_mtime); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files_mtime)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::mtime() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 235 "RPM_Files.xs"
    RETVAL = rpmfiFMtime(Files);
#line 842 "RPM_Files.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_RPM__Files__nlink); /* prototype to pass -Wmissing-prototypes */
XS(XS_RPM__Files__nlink)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "Files");
    {
	rpmfi	Files;
	int	RETVAL;
	dXSTARG;

    if (sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG))
        Files = (rpmfi)SvIV((SV*)SvRV( ST(0) ));
    else {
        warn( "RPM::Files::_nlink() -- Files is not a blessed SV reference" );
        XSRETURN_UNDEF;
    };
#line 243 "RPM_Files.xs"
    RETVAL = rpmfiFNlink(Files);
#line 872 "RPM_Files.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_RPM__Files); /* prototype to pass -Wmissing-prototypes */
XS(boot_RPM__Files)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("RPM::Files::new", XS_RPM__Files_new, file, "$$;$");
        (void)newXSproto_portable("RPM::Files::DESTROY", XS_RPM__Files_DESTROY, file, "$");
        (void)newXSproto_portable("RPM::Files::count", XS_RPM__Files_count, file, "$");
        (void)newXSproto_portable("RPM::Files::init", XS_RPM__Files_init, file, "$");
        (void)newXSproto_portable("RPM::Files::next", XS_RPM__Files_next, file, "$");
        (void)newXSproto_portable("RPM::Files::count_dir", XS_RPM__Files_count_dir, file, "$");
        (void)newXSproto_portable("RPM::Files::init_dir", XS_RPM__Files_init_dir, file, "$");
        (void)newXSproto_portable("RPM::Files::next_dir", XS_RPM__Files_next_dir, file, "$");
        (void)newXSproto_portable("RPM::Files::_compare", XS_RPM__Files__compare, file, "$$");
        (void)newXSproto_portable("RPM::Files::filename", XS_RPM__Files_filename, file, "$");
        (void)newXSproto_portable("RPM::Files::dirname", XS_RPM__Files_dirname, file, "$");
        (void)newXSproto_portable("RPM::Files::basename", XS_RPM__Files_basename, file, "$");
        (void)newXSproto_portable("RPM::Files::fflags", XS_RPM__Files_fflags, file, "$");
        (void)newXSproto_portable("RPM::Files::mode", XS_RPM__Files_mode, file, "$");
        (void)newXSproto_portable("RPM::Files::digest", XS_RPM__Files_digest, file, "$");
        (void)newXSproto_portable("RPM::Files::link", XS_RPM__Files_link, file, "$");
        (void)newXSproto_portable("RPM::Files::user", XS_RPM__Files_user, file, "$");
        (void)newXSproto_portable("RPM::Files::group", XS_RPM__Files_group, file, "$");
        (void)newXSproto_portable("RPM::Files::inode", XS_RPM__Files_inode, file, "$");
        (void)newXSproto_portable("RPM::Files::size", XS_RPM__Files_size, file, "$");
        (void)newXSproto_portable("RPM::Files::dev", XS_RPM__Files_dev, file, "$");
        (void)newXSproto_portable("RPM::Files::color", XS_RPM__Files_color, file, "$");
        (void)newXSproto_portable("RPM::Files::class", XS_RPM__Files_class, file, "$");
        (void)newXSproto_portable("RPM::Files::mtime", XS_RPM__Files_mtime, file, "$");
        (void)newXSproto_portable("RPM::Files::_nlink", XS_RPM__Files__nlink, file, "$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

